#jwt
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      #a day
      expiration: 86400000
      #a week
      refresh-token:
        expiration: 604800000

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    username: root
    password: Nhuan123

    url: jdbc:mysql://localhost:3306/chatapp?createDatabaseIfNotExist=true&useUnicode=true&character_set_server=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  mvc:
    static-path-pattern: upload/**
  web:
    resources:
      static-locations: file:upload/