spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    username: root
    password: Nhuan123

    url: jdbc:mysql://localhost:3306/chatapp
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always